# Generated by Django 4.1 on 2022-09-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='multijugador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='juego',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
