# Generated by Django 4.1 on 2022-09-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_genero_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='juegos',
        ),
    ]
