# Generated by Django 4.1 on 2022-09-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_compra_juegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.proveedor'),
        ),
    ]
