# Generated by Django 4.1 on 2022-09-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_compra_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.proveedor'),
        ),
    ]
