# Generated by Django 4.1 on 2022-09-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_compra_id_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_permiso',
            new_name='id_rol',
        ),
    ]
