# Generated by Django 4.1.2 on 2022-10-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_id_permiso_usuario_id_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='apellido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrados'), ('C', 'Cliente'), ('E', 'Empleado')], default='C', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
