# Generated by Django 4.1.2 on 2022-10-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_empleado_id_usuario_remove_rol_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
