# Generated by Django 4.1.2 on 2022-11-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_juego_imagen_alter_juego_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(default='webapp/images/default.jpg', upload_to='webapp/images'),
        ),
    ]
