# Generated by Django 4.1.2 on 2022-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_juego_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('C', 'Cliente'), ('E', 'Empleado')], default='C', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
