# Generated by Django 4.1.2 on 2022-11-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_detalle',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta_detalle',
            name='subtotal',
        ),
    ]
