# Generated by Django 4.1.3 on 2022-11-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_venta_detalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_detalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
