# Generated by Django 4.1.3 on 2022-12-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_venta_detalle_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.FloatField(),
        ),
    ]
